// Code generated by mockery v2.42.0. DO NOT EDIT.

package mock

import mock "github.com/stretchr/testify/mock"

// Keyring is an autogenerated mock type for the Keyring type
type Keyring struct {
	mock.Mock
}

// Delete provides a mock function with given fields: service, user
func (_m *Keyring) Delete(service string, user string) error {
	ret := _m.Called(service, user)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(service, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: service, user
func (_m *Keyring) Get(service string, user string) (string, error) {
	ret := _m.Called(service, user)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(service, user)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(service, user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(service, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: service, user, password
func (_m *Keyring) Set(service string, user string, password string) error {
	ret := _m.Called(service, user, password)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(service, user, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewKeyring creates a new instance of Keyring. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeyring(t interface {
	mock.TestingT
	Cleanup(func())
}) *Keyring {
	mock := &Keyring{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
