// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewKeyring creates a new instance of Keyring. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeyring(t interface {
	mock.TestingT
	Cleanup(func())
}) *Keyring {
	mock := &Keyring{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Keyring is an autogenerated mock type for the Keyring type
type Keyring struct {
	mock.Mock
}

type Keyring_Expecter struct {
	mock *mock.Mock
}

func (_m *Keyring) EXPECT() *Keyring_Expecter {
	return &Keyring_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type Keyring
func (_mock *Keyring) Delete(service string, user string) error {
	ret := _mock.Called(service, user)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(service, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Keyring_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Keyring_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - service string
//   - user string
func (_e *Keyring_Expecter) Delete(service any, user any) *Keyring_Delete_Call {
	return &Keyring_Delete_Call{Call: _e.mock.On("Delete", service, user)}
}

func (_c *Keyring_Delete_Call) Run(run func(service string, user string)) *Keyring_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Keyring_Delete_Call) Return(err error) *Keyring_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Keyring_Delete_Call) RunAndReturn(run func(service string, user string) error) *Keyring_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAll provides a mock function for the type Keyring
func (_mock *Keyring) DeleteAll(service string) error {
	ret := _mock.Called(service)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(service)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Keyring_DeleteAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAll'
type Keyring_DeleteAll_Call struct {
	*mock.Call
}

// DeleteAll is a helper method to define mock.On call
//   - service string
func (_e *Keyring_Expecter) DeleteAll(service any) *Keyring_DeleteAll_Call {
	return &Keyring_DeleteAll_Call{Call: _e.mock.On("DeleteAll", service)}
}

func (_c *Keyring_DeleteAll_Call) Run(run func(service string)) *Keyring_DeleteAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Keyring_DeleteAll_Call) Return(err error) *Keyring_DeleteAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Keyring_DeleteAll_Call) RunAndReturn(run func(service string) error) *Keyring_DeleteAll_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type Keyring
func (_mock *Keyring) Get(service string, user string) (string, error) {
	ret := _mock.Called(service, user)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(service, user)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(service, user)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(service, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Keyring_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Keyring_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - service string
//   - user string
func (_e *Keyring_Expecter) Get(service any, user any) *Keyring_Get_Call {
	return &Keyring_Get_Call{Call: _e.mock.On("Get", service, user)}
}

func (_c *Keyring_Get_Call) Run(run func(service string, user string)) *Keyring_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Keyring_Get_Call) Return(s string, err error) *Keyring_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Keyring_Get_Call) RunAndReturn(run func(service string, user string) (string, error)) *Keyring_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type Keyring
func (_mock *Keyring) Set(service string, user string, password string) error {
	ret := _mock.Called(service, user, password)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = returnFunc(service, user, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Keyring_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type Keyring_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - service string
//   - user string
//   - password string
func (_e *Keyring_Expecter) Set(service any, user any, password any) *Keyring_Set_Call {
	return &Keyring_Set_Call{Call: _e.mock.On("Set", service, user, password)}
}

func (_c *Keyring_Set_Call) Run(run func(service string, user string, password string)) *Keyring_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Keyring_Set_Call) Return(err error) *Keyring_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Keyring_Set_Call) RunAndReturn(run func(service string, user string, password string) error) *Keyring_Set_Call {
	_c.Call.Return(run)
	return _c
}
