// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage[V any](t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage[V] {
	mock := &Storage[V]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Storage is an autogenerated mock type for the Storage type
type Storage[V any] struct {
	mock.Mock
}

type Storage_Expecter[V any] struct {
	mock *mock.Mock
}

func (_m *Storage[V]) EXPECT() *Storage_Expecter[V] {
	return &Storage_Expecter[V]{mock: &_m.Mock}
}

// Delete provides a mock function for the type Storage
func (_mock *Storage[V]) Delete(service string, key string) error {
	ret := _mock.Called(service, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(service, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Storage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Storage_Delete_Call[V any] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - service string
//   - key string
func (_e *Storage_Expecter[V]) Delete(service any, key any) *Storage_Delete_Call[V] {
	return &Storage_Delete_Call[V]{Call: _e.mock.On("Delete", service, key)}
}

func (_c *Storage_Delete_Call[V]) Run(run func(service string, key string)) *Storage_Delete_Call[V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Storage_Delete_Call[V]) Return(err error) *Storage_Delete_Call[V] {
	_c.Call.Return(err)
	return _c
}

func (_c *Storage_Delete_Call[V]) RunAndReturn(run func(service string, key string) error) *Storage_Delete_Call[V] {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type Storage
func (_mock *Storage[V]) Get(service string, key string) (V, error) {
	ret := _mock.Called(service, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 V
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (V, error)); ok {
		return returnFunc(service, key)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) V); ok {
		r0 = returnFunc(service, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(V)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(service, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Storage_Get_Call[V any] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - service string
//   - key string
func (_e *Storage_Expecter[V]) Get(service any, key any) *Storage_Get_Call[V] {
	return &Storage_Get_Call[V]{Call: _e.mock.On("Get", service, key)}
}

func (_c *Storage_Get_Call[V]) Run(run func(service string, key string)) *Storage_Get_Call[V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Storage_Get_Call[V]) Return(v V, err error) *Storage_Get_Call[V] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Storage_Get_Call[V]) RunAndReturn(run func(service string, key string) (V, error)) *Storage_Get_Call[V] {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type Storage
func (_mock *Storage[V]) Set(service string, key string, value V) error {
	ret := _mock.Called(service, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, V) error); ok {
		r0 = returnFunc(service, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Storage_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type Storage_Set_Call[V any] struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - service string
//   - key string
//   - value V
func (_e *Storage_Expecter[V]) Set(service any, key any, value any) *Storage_Set_Call[V] {
	return &Storage_Set_Call[V]{Call: _e.mock.On("Set", service, key, value)}
}

func (_c *Storage_Set_Call[V]) Run(run func(service string, key string, value V)) *Storage_Set_Call[V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 V
		if args[2] != nil {
			arg2 = args[2].(V)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Storage_Set_Call[V]) Return(err error) *Storage_Set_Call[V] {
	_c.Call.Return(err)
	return _c
}

func (_c *Storage_Set_Call[V]) RunAndReturn(run func(service string, key string, value V) error) *Storage_Set_Call[V] {
	_c.Call.Return(run)
	return _c
}
