dir: mock
structname: '{{.InterfaceName}}'
pkgname: mock
filename: "{{ .InterfaceName | snakecase }}.go"
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/zalando/go-keyring:
    config:
      all: true
  go.nhat.io/secretstorage:
    config:
      exclude-interface-regex: configurableKeyringStorage|Option|.+(Func|Option)
      include-interface-regex: .+
